server:
  port: 8081
spring:
  application:
    name: backend-config-service
  cloud:
    config:
      server:
        git:
          default label: master
          uri: https://github.com/dhorol/Tingeso_proyecto4
          search-paths: "config-data"



